# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_qFMQYZnIVHN-JQY1d74NirdwsdPtAUp
"""



import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import pickle

# ---------------- HEART DISEASE ----------------
heart = pd.read_csv("/content/heart_desease_data.csv")

X = heart.drop("target", axis=1)
y = heart["target"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

heart_model = RandomForestClassifier()
heart_model.fit(X_train, y_train)

pickle.dump(heart_model, open("heart_model.pkl","wb"))

print("Heart model saved")


# ---------------- DIABETES ----------------
diabetes = pd.read_csv("/content/diabetes.csv")

X = diabetes.drop("Outcome", axis=1)
y = diabetes["Outcome"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

diabetes_model = RandomForestClassifier()
diabetes_model.fit(X_train, y_train)

pickle.dump(diabetes_model, open("diabetes_model.pkl","wb"))

print("Diabetes model saved")


# ---------------- STROKE ----------------
stroke = pd.read_csv("/content/healthcare-dataset-stroke-data.csv")

# Drop 'id' column as it's an identifier
stroke = stroke.drop("id", axis=1)

# Handle 'Other' gender category if present (e.g., remove, or treat as a valid category)
# For simplicity, dropping rows with 'Other' gender as it can be problematic for one-hot encoding if not handled carefully.
stroke = stroke[stroke['gender'] != 'Other']

# Handle missing values in 'bmi'
# Convert 'N/A' or similar non-numeric entries to NaN, then impute with the mean
stroke['bmi'] = pd.to_numeric(stroke['bmi'], errors='coerce')
stroke['bmi'].fillna(stroke['bmi'].mean(), inplace=True)

# Identify categorical columns for one-hot encoding
categorical_cols = ['gender', 'ever_married', 'work_type', 'Residence_type', 'smoking_status']
stroke = pd.get_dummies(stroke, columns=categorical_cols, drop_first=True)

X = stroke.drop("stroke", axis=1)
y = stroke["stroke"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

stroke_model = RandomForestClassifier()
stroke_model.fit(X_train, y_train)

pickle.dump(stroke_model, open("stroke_model.pkl","wb"))

print("Stroke model saved")

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import pickle

# ---------------- HEART DISEASE ----------------
heart = pd.read_csv("heart_desease_data.csv")

heart = heart[["age","sex","cp","trestbps","chol","target"]]

X = heart.drop("target", axis=1)
y = heart["target"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

heart_model = RandomForestClassifier()
heart_model.fit(X_train, y_train)

pickle.dump(heart_model, open("heart_model.pkl","wb"))

print("Heart model saved")


# ---------------- DIABETES ----------------
diabetes = pd.read_csv("diabetes.csv")

diabetes = diabetes[["Pregnancies","Glucose","BloodPressure","BMI","Age","Outcome"]]

X = diabetes.drop("Outcome", axis=1)
y = diabetes["Outcome"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

diabetes_model = RandomForestClassifier()
diabetes_model.fit(X_train, y_train)

pickle.dump(diabetes_model, open("diabetes_model.pkl","wb"))

print("Diabetes model saved")


# ---------------- STROKE ----------------
stroke = pd.read_csv("healthcare-dataset-stroke-data.csv")

stroke = stroke[["age","hypertension","heart_disease","avg_glucose_level","bmi","stroke"]]

stroke["bmi"].fillna(stroke["bmi"].mean(), inplace=True)

X = stroke.drop("stroke", axis=1)
y = stroke["stroke"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

stroke_model = RandomForestClassifier()
stroke_model.fit(X_train, y_train)

pickle.dump(stroke_model, open("stroke_model.pkl","wb"))

print("Stroke model saved")

!streamlit run app.py
